/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

type notification = {
    title: string;
    body: string;
};

self.addEventListener('push', (event: any) => {
    console.log("SW catch push");
    console.log('=====');
    console.log(event);
    console.log('=====');
    console.log(event.data);
    console.log('=====');
    console.log(event.data.arrayBuffer);
    console.log('=====');
    console.log(event.data.json);
    console.log('=====');
    console.log(event.data.text);
    /*
    event.waitUntil(self.registration.showNotification(title, body))*/
    /*let notification = new Notification(title, {
        body: message,
        tag: 'simple-push-demo-notification',
        icon: icon
    });

    /*notification.addEventListener('click', function() {
        console.log('You CLICKED ON NOTIF !!!');
        /*if (clients.openWindow) {
            clients.openWindow('https://example.blog.com/2015/03/04/something-new.html');
        }
    });*/

    try {
        let notification_data;
        if (event.data) {
            notification_data = event.data.json();
        }
        let title = notification_data.title || "Something Has Happened";
        let message = notification_data.message || "Here's something you might want to check out.";
        let icon = "images/favicon-16x16.png";

        let body: object;


        if (event.data && event.data.json) {
            //You can set an original message by passing it on the event.
            body = event.data.json();
        } else {
            body = {body: 'NONO NON ON ON ONO NON ', title: 'NOOOOOOOO'}
        }


        console.log("SALUt");
        console.log(body);
        console.log(typeof body);

        const options = {
            // @ts-ignore
            body: body.body,
            icon: icon,
            vibrate: [100, 50, 100],
            data: {
                dateOfArrival: Date.now(),
                primaryKey: 1,
            },
        };

        event.waitUntil(
            // @ts-ignore
            self.registration.showNotification(body.title, options))
    }
    catch (e) {
        console.log('SW pushlistn error ');
        console.log(e);
    }
})
